# -*- coding: utf-8 -*-
"""Question 1 - Practice Question -Exam 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Z4wXVJsbln5hcG0Musaymok0JqcBeip

# Question1
Write a Python program that provides the following options for number conversions:

- Convert a decimal number to binary.
- Convert a binary number to decimal.
- Convert a decimal number to hexadecimal.
- Convert a hexadecimal number to decimal.
- Exit the program.
- Your program should include four separate functions, each dedicated to one type of conversion:
  - Function 1: Converts a decimal number to binary.
  - Function 2: Converts a binary number to decimal.
  - Function 3: Converts a decimal number to hexadecimal.
  - Function 4: Converts a hexadecimal number to decimal.

- The program should prompt the user to select an option. After a conversion is performed, the user should be able to either choose another option or exit the program by selecting option 5.

### Without using the inbuilt function
"""

def decimalToconBinary(num):
  binary = ''
  if num ==0:
    binary = '0'

  elif num ==1:
    binary = '1'
  else:
    while(num > 0):
      remainder = num % 2
      if f'{remainder}' == 0:
        binary = f'{remainder}' + binary
      else:
        binary = f'{remainder}' + binary
      num = num // 2

  return binary

decimalToconBinary(20)

def decimalToHexadecimal(num):
  conversion_table = {0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: 'A', 11: 'B', 12: 'C', 13: 'D', 14: 'E', 15: 'F'}

  hexadecimal = ''
  if num ==0:
    hexadecimal = 0 + hexadecimal
  else:
    while(num > 0):
      remainder = num % 16
      hexadecimal = conversion_table[remainder] + hexadecimal
      num = num // 16

  return hexadecimal

decimalToHexadecimal(10)

def binaryToDecimal(binary_str):
    decimal = 0
    binary_str = binary_str[::-1]
    for i in range(len(binary_str)):
        if binary_str[i] == '1':
            decimal += 2 ** i
    return decimal


print(binaryToDecimal('10100'))

def hexToDecimal(hex_str):

    hex_dict = {
        '0': 0, '1': 1, '2': 2, '3': 3,
        '4': 4, '5': 5, '6': 6, '7': 7,
        '8': 8, '9': 9, 'A': 10, 'B': 11,
        'C': 12, 'D': 13, 'E': 14, 'F': 15
    }

    decimal = 0
    hex_str = hex_str.upper()

    for i, char in enumerate(reversed(hex_str)):
        decimal += hex_dict[char] * (16 ** i)

    return decimal


print(hexToDecimal('B1A'))

(16**0 * 10)+(16**1 *1)+(16**2 * 11)

def decimal_to_binary(num):
    """This func converts a decimal number to binary."""

    return bin(num)

def binary_to_decimal(num):
    """This func converts binary number to decimal."""
    return int(num, 2)

def decimal_to_hexadecimal(num):
    """ This func convers a decimal number to hexadecimal."""
    return hex(num)

def hexadecimal_to_decimal(num):
    """This func converts a hexadecimal number to decimal."""
    return int(num, 16)


while True:
    print("\nNumber Conversion Menu:")
    print("1. Convert Decimal to Binary")
    print("2. Convert Binary to Decimal")
    print("3. Convert Decimal to Hexadecimal")
    print("4. Convert Hexadecimal to Decimal")
    print("5. Exit")

    choice = input("Enter your choice (1/2/3/4/5): ")

    if choice == "1":
        num = int(input("Enter a decimal number: "))
        print(f"Binary: {decimal_to_binary(num)}")

    elif choice == "2":
        num = input("Enter a binary number: ")
        print(f"Decimal: {binary_to_decimal(num)}")

    elif choice == "3":
        num = int(input("Enter a decimal number: "))
        print(f"Hexadecimal: {decimal_to_hexadecimal(num)}")

    elif choice == "4":
        num = input("Enter a hexadecimal number: ")
        print(f"Decimal: {hexadecimal_to_decimal(num)}")

    elif choice == "5":
        print("Thanks for using the program. Goodbye!")
        break

    else:
        print("Invalid choice. Please select a valid option.")

print(int('100A', 2))

int('1A', 16)