# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ghfzcQcgtCSosxATqS4Vx0NaLwqMboF
"""

# Question: 1(A)
class Member:
    def __init__(self, name, age, membership_type,goal):
        self.name = name
        self.age = age
        self.membership_type = membership_type
        self.goal = goal
        self.trainer = None
        self.workout_schedule = []
        self.progress = {}

    def assign_trainer(self, trainer):
        self.trainer = trainer

    def add_workout_schedule(self, schedule):
        self.workout_schedule.append(schedule)

    def update_progress(self, metric, value):
        self.progress[metric] = value

    def display_details(self):
        print(f"Member Name: {self.name}")
        print(f"Age: {self.age}")
        print(f"Membership Type: {self.membership_type}")
        if self.trainer:
            print(f"Trainer: {self.trainer}")
        else:
            print("Trainer: Not Assigned")
        print("Workout Schedule:")
        for schedule in self.workout_schedule:
            print(f" - {schedule}")
        print("Progress:")
        for metric, value in self.progress.items():
            print(f" - {metric}: {value}")

# Adding three members
members = [
    Member("Alice", 30, "Monthly","Weight Loss" ),
    Member("Bob", 40, "Annual", "Muscle Gain"),
    Member("Charlie", 25, "Monthly", "General Fitness"),
]

"""### Displaying Details"""

for member in members:
    print("\n" + "-" * 30)
    member.display_details()

"""### Add Schedule"""

schedules = {
    "Alice": ["Monday 6 PM - Cardio", "Wednesday 6 PM - HIIT"],
    "Bob": ["Tuesday 7 PM - Strength Training", "Thursday 7 PM - Weight Lifting"],
    "Charlie": ["Monday 7 AM - Yoga", "Friday 7 AM - Pilates"],
}

for member in members:
    for schedule in schedules[member.name]:
        member.add_workout_schedule(schedule)

"""### Add trainer"""

trainers = {
    "Weight Loss": "Trainer John",
    "Muscle Gain": "Trainer Sarah",
    "General Fitness": "Trainer Mike",
}
for member in members:
    member.assign_trainer(trainers[member.goal])

for member in members:
    print("\n" + "-" * 30)
    member.display_details()